name: pizzaparty
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.1 <3.0.0'
dependencies:
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.15
  provider: ^5.0.0
  get:
  lottie: ^1.4.2
  webview_flutter: ^3.0.4
  google_fonts: ^2.1.8
  firebase_messaging: ^14.0.3

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.9
  flutter_launcher_icons: ^0.10.0


flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/pizzalogotransparent.png"

flutter: 
  uses-material-design: true
  assets:
    - packages/pizzaparty/assets/json_animations/38964-group-of-people-communicating.zip
    - packages/pizzaparty/assets/json_animations/87237-pizza-preloader.zip
    - packages/pizzaparty/assets/json_animations/67226-food-app-interaction.zip
    - packages/pizzaparty/assets/json_animations/63703-pizza.zip
    - packages/pizzaparty/assets/json_animations/64809-pizza-loading.zip
    - packages/pizzaparty/assets/images/3786128removebgpreview1.png
    - packages/pizzaparty/assets/images/group.svg
    - packages/pizzaparty/assets/images/ellipse1.png
    - packages/pizzaparty/assets/images/arrow1.svg
    - packages/pizzaparty/assets/images/line1.svg
    - packages/pizzaparty/assets/images/ellipse2.png
    - packages/pizzaparty/assets/images/ellipse3.png
    - packages/pizzaparty/assets/images/arrow2.svg
    - packages/pizzaparty/assets/images/arrow3.svg
    - packages/pizzaparty/assets/images/ellipse6.png
    - packages/pizzaparty/assets/images/ellipse5.png
    - packages/pizzaparty/assets/images/ellipse4.png
    - packages/pizzaparty/assets/images/ellipse7.png
    - packages/pizzaparty/assets/images/ellipse1_1.png
    - packages/pizzaparty/assets/images/ellipse1_2.png
    - packages/pizzaparty/assets/images/ellipse2_1.png
    - packages/pizzaparty/assets/images/ellipse2_2.png
    - packages/pizzaparty/assets/images/size_l.png
    - packages/pizzaparty/assets/images/size_m.png
    - packages/pizzaparty/assets/images/size_s.png
    - packages/pizzaparty/assets/images/size_xl.png
    - packages/pizzaparty/assets/images/frameintro.jpg
    - packages/pizzaparty/assets/images/pizzalogotransparent.png
    - packages/pizzaparty/assets/index.html

flutter_native_splash:
  image: lib/assets/images/pizzalogotransparent.png
  color: "#FFB74D"